---
engines:
  swiftlint:
   exclude_paths:
     - '**/*Tests.swift'    
 duplication:
   exclude_paths:
     - '**/*Tests.swift'
exclude_paths:
  - 'docs/**'
  - 'fastlane/**'
  - '.github/**'
  - '*.md'
  - 'Tests/MockSwiftTests/XCTestManifests.swift'